### ISSUE TITLE
make all command unable to create "dist" directory

### ISSUE THREAD

**Issue by ChinmoyPadhi** [maikuroashi/mongodb-datasource#1]
Hi,
I am new to grafana , I have come across this plugin which can be used for mongodb
I am trying to build using "make all" command but getting following errors
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
$ npm --version
6.14.15
$ make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

The directory mongodb-datasource has following list of files
$ ls -lart
total 876
drwxrwxr-x    3 vbox vbox     62 Jan 20 12:44 ..
drwxrwxr-x    2 vbox vbox     25 Jan 20 12:44 .vscode
-rw-rw-r--    1 vbox vbox   4609 Jan 20 12:44 README.md
-rw-rw-r--    1 vbox vbox    109 Jan 20 12:44 .prettierrc.js
-rw-rw-r--    1 vbox vbox    285 Jan 20 12:44 Makefile
-rw-rw-r--    1 vbox vbox    324 Jan 20 12:44 Magefile.go
-rw-rw-r--    1 vbox vbox  11357 Jan 20 12:44 LICENSE
-rw-rw-r--    1 vbox vbox    378 Jan 20 12:44 .gitignore
drwxrwxr-x    3 vbox vbox     23 Jan 20 12:44 .github
-rw-rw-r--    1 vbox vbox     53 Jan 20 12:44 CHANGELOG.md
-rw-rw-r--    1 vbox vbox    356 Jan 20 12:44 jest.config.js
-rw-rw-r--    1 vbox vbox  27598 Jan 20 12:44 go.sum
-rw-rw-r--    1 vbox vbox    157 Jan 20 12:44 go.mod
drwxrwxr-x    2 vbox vbox     50 Jan 20 12:44 dockerdev
drwxrwxr-x    5 vbox vbox     61 Jan 20 12:44 pkg
-rw-rw-r--    1 vbox vbox    680 Jan 20 12:44 package.json
-rw-rw-r--    1 vbox vbox    232 Jan 20 12:44 tsconfig.json
drwxrwxr-x    3 vbox vbox    137 Jan 20 12:44 src
drwxrwxr-x    8 vbox vbox    163 Jan 20 12:44 .git
drwxrwxr-x 1115 vbox vbox  32768 Jan 20 12:57 node_modules
-rw-rw-r--    1 vbox vbox 746682 Jan 20 12:57 package-lock.json
drwxrwxr-x   10 vbox vbox   4096 Jan 20 12:57 .
drwxrwxr-x    2 vbox vbox     23 Jan 20 12:57 coverage

$ make all
npm install
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @types/anymatch@3.0.0: This is a stub types definition. anymatch provides its own type definitions, so you do not need this installed.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

> core-js@2.6.12 postinstall /home/vbox/test/mongodb-datasource/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.10.0 postinstall /home/vbox/test/mongodb-datasource/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-environment-jsdom-fifteen/node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-window@1.8.5 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-window@1.8.5 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slate-react-placeholder@0.2.9 requires a peer of slate-react@>=0.22.0 but none is installed. You must install peer dependencies yourself.
npm WARN cssnano@5.0.15 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN cssnano-preset-default@5.1.10 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN css-declaration-sorter@6.1.4 requires a peer of postcss@^8.0.9 but none is installed. You must install peer dependencies yourself.
npm WARN cssnano-utils@3.0.0 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-calc@8.2.2 requires a peer of postcss@^8.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-colormin@5.2.3 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-convert-values@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-discard-comments@5.0.1 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-discard-duplicates@5.0.1 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-discard-empty@5.0.1 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-discard-overridden@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-merge-longhand@5.0.4 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-merge-rules@5.0.4 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-minify-font-values@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-minify-gradients@5.0.4 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-minify-params@5.0.3 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-minify-selectors@5.1.1 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-charset@5.0.1 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-display-values@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-positions@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-repeat-style@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-string@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-timing-functions@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-unicode@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-url@5.0.4 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-normalize-whitespace@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-ordered-values@5.0.3 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-reduce-initial@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-reduce-transforms@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-svgo@5.0.3 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-unique-selectors@5.0.2 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN stylehacks@5.0.1 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN maikuroashi-mongodb-datasource@1.0.0 No repository field.

added 2015 packages from 972 contributors and audited 2019 packages in 162.283s

147 packages are looking for funding
  run `npm fund` for details

found 15 vulnerabilities (5 moderate, 9 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
npm run-script build

> maikuroashi-mongodb-datasource@1.0.0 build /home/vbox/test/mongodb-datasource
> grafana-toolkit plugin:build

  Using Node.js v14.18.3
  Using @grafana/toolkit v8.3.4
✔ Preparing
⠙ Linting  =============

  WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

  You may find that it works just fine, or you may not.

  SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.4.0

  YOUR TYPESCRIPT VERSION: 4.4.3

  Please only submit bug reports when using the officially supported version.

  =============
✔ Linting
No tests found, exiting with code 0
✔ Running tests
✖ PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
  Trace: Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
  Migration guide for end-users:
  https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
      at Processor.normalize (/home/vbox/test/mongodb-datasource/node_modules/postcss/lib/processor.js:167:15)
      at new Processor (/home/vbox/test/mongodb-datasource/node_modules/postcss/lib/processor.js:56:25)
      at postcss (/home/vbox/test/mongodb-datasource/node_modules/postcss/lib/postcss.js:55:10)
      at cssnanoPlugin (/home/vbox/test/mongodb-datasource/node_modules/cssnano/dist/index.js:158:31)
      at getDefaultProcessor (/home/vbox/test/mongodb-datasource/node_modules/optimize-css-assets-webpack-plugin/src/index.js:9:19)
      at new OptimizeCssAssetsWebpackPlugin (/home/vbox/test/mongodb-datasource/node_modules/optimize-css-assets-webpack-plugin/src/index.js:30:9)
      at /home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/src/config/webpack.plugin.config.js:160:25
      at step (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:124:57)
      at /home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:75
      at new Promise (<anonymous>)
      at __awaiter (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:113:16)
      at getBaseWebpackConfig (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/src/config/webpack.plugin.config.js:148:78)
      at /home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/src/config/webpack.plugin.config.js:279:42
      at step (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:124:57)
      at /home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:31:33
      at step (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:143:27)
      at Object.throw (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:124:57)
      at rejected (/home/vbox/test/mongodb-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:115:69)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! maikuroashi-mongodb-datasource@1.0.0 build: `grafana-toolkit plugin:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the maikuroashi-mongodb-datasource@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vbox/.npm/_logs/2022-01-20T07_27_16_007Z-debug.log
make: *** [dist/module.js] Error 1
```

**Comment by maikuroashi** [comment]
Hi,

The issue is down to the version of node you are using v14.18.3, if I build with that version I get the same error.
You need to build with the latest LTS release of node, currently v16.13.2.
Building with node v14.x will mess up the versions in the `package-lock.json` file so you need to reset any changes:

```sh
git reset HEAD --hard
```

I have pushed up a change which documents the minimum versions of the required development tools and updates the `package-lock.json` with the latest versions of the dependencies which you might want to grab first.

Then make sure to install the required development tools Go and Mage that are now documented in the README.md.
The front-end and back-end parts of the plugin should then build into the `dist` dir with a:

```sh
make clean all
```
